apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: devops-rs-nginx
spec:
  replicas: 10
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - dev
          - uat
          - qa
          - prod
  template:
    metadata:
      name: devops-rs-nginx
      labels:
        app: dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
