apiVersion: v1
kind: ReplicationController
metadata:
  name: devops-rc-nginx
spec:
  replicas: 5
  selector:
    app: devops-rc-nginx
  template:
    metadata:
      name: devops-rc-nginx
      labels:
        app: devops-rc-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
