apiVersion: v1
kind: Pod
metadata:
  name: devopspod1
  labels:
    name: devopspod1
spec:
  containers:
  - name: devopspod1
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
